grubfood_2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('webkiosk/', include('webkiosk.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webkiosk/urls.py
from django.urls import path
from . import views

app_name='webkiosk'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('register/', views.registerpage, name='register'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    
    #For regular non-admin users
    path('userprofile/', views.userprofile, name='userprofile'),
    
    path('userorders/', views.userorders, name='userorders'),
    path('userorders/new/', views.userneworder, name='userneworder'),
    path('userorders/<int:pk>/', views.userorderdetails, name='userorderdetails'),
    path('userorders/<int:pk>/edit/', views.userorderupdate, name='userorderupdate'),
    path('userorders/<int:pk>/delete/', views.userorderdelete, name='userorderdelete'),
    
    path('usernewitem/<int:pk>/new/', views.usernewitem, name='usernewitem'),
    path('usernewitem/<int:pk>/edit/', views.userupdateitem, name='useritemupdate'),
    path('usernewitem/<int:pk>/delete/', views.userdeleteitem, name='useritemdelete'),
    
    path('products/', views.products, name='products'),
    path('products/<int:pk>/', views.productdetail, name='productdetail'),
    
    # For admin users
    path('dashboard/', views.dashboard, name='dashboard'),
    
    # Food
    path('food/', views.listfood, name='food-list'),
    path('food/new/', views.createfood, name='food-create'),
    path('food/<int:pk>/', views.detailfood, name='food-detail'),
    path('food/<int:pk>/edit/', views.updatefood, name='food-edit'),
    path('food/<int:pk>/delete/', views.deletefood, name='food-delete'),
    
    # Customer
    path('customer/', views.listcustomer, name='customer-list'),
    path('customer/new/', views.createcustomer, name='customer-create'),
    path('customer/<int:pk>/', views.detailcustomer, name='customer-detail'),
    path('customer/<int:pk>/edit/', views.updatecustomer, name='customer-edit'),
    path('customer/<int:pk>/delete/', views.deletecustomer, name='customer-delete'),
    
    #Order
    path('order/', views.listorder, name='order-list'),
    path('order/new/', views.createorder, name='order-create'),
    path('order/<int:pk>/', views.detailorder, name='order-detail'),
    path('order/<int:pk>/edit/', views.updateorder, name='order-edit'),
    path('order/<int:pk>/delete/', views.deleteorder, name='order-delete'),
    
    #Order Items
    path('orderitem/<int:pk>/new/', views.addorderitem, name='orderitem-create'),
    path('orderitem/<int:pk>/edit/', views.updateorderitem, name='orderitem-update'),
    path('orderitem/<int:pk>/delete/', views.deleteorderitem, name='orderitem-delete'),
]

webkiosk/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.id}: {self.firstname}, {self.lastname}, {self.address}, {self.city}'
    
class Food(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.id}: {self.name}, {self.description}, {self.price}'
    
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
class Order(models.Model):
    PAYMENT_MODE_CHOICES = [
        #tuples
        ('CH', 'Cash'),
        ('CD', 'Card'),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE) 
    orderdatetime = models.DateTimeField(auto_now_add=True) 
    paymentmode = models.CharField(max_length=2, choices=PAYMENT_MODE_CHOICES) 

    # def __str__(self):
    #     return f'{self.id}: {self.customer.firstname} {self.customer.lastname}, {self.food.name}, {self.quantity}, {self.paymentmode}, {self.orderdatetime}'
    
    def __str__(self):
        return f'{self.id}: {self.customer.firstname} {self.customer.lastname}, {self.paymentmode}, {self.orderdatetime}'


class OrderItem(models.Model):

    quantity = models.IntegerField(default=1)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.order.customer.firstname} {self.order.customer.lastname}, {self.food.name}, {self.quantity}'

    def total_price(self):
        return self.food.price * self.quantity

webkiosk/forms.py
from django.forms import ModelForm, HiddenInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Customer, Food, Order, OrderItem

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'description', 'price']
        placeholders = {
            "name": "Name",
            "description": "Description",
            "price": "Price"
        }
        
class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['firstname', 'lastname', 'address', 'city']
        
class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'paymentmode']

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['order', 'food', 'quantity']
        widgets = {
            'order': HiddenInput(),
        }

class CustomerOrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'paymentmode']
        widgets = {
            'customer': HiddenInput(),
        }

# FOR THE LOGIN FORM
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

webkiosk/views.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from .models import Customer, Food, Order, OrderItem
from .forms import FoodForm, CustomerForm, OrderForm, OrderItemForm, CreateUserForm
from .decorators import unauthenticated_user, allowed_users, admin_only

# Create your views here.
# main views
def index(request):
    return render(request, 'webkiosk/welcome.html')

def about(request):
    return render(request, 'webkiosk/about.html')

@unauthenticated_user
def registerpage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            Customer.objects.create(
                user=user,
            )
            
            messages.success(request, 'Account was created for ' + username)
            
            return redirect('webkiosk:login')
        
    context = {'form':form}
    return render(request, 'webkiosk/register.html', context)

@unauthenticated_user
def loginpage(request): 
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('webkiosk:dashboard')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'webkiosk/signin.html', context)
    
def logoutuser(request):
    logout(request)
    return redirect('webkiosk:login')

#################
# customer views
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userprofile(request):
    customer = request.user.customer
    form = CustomerForm(instance=customer)
    
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
            
    context={'form':form}
    return render(request, 'webkiosk/user_profile.html', context)

def products(request):
    context = {
        'products': Food.objects.all()
    }
    return render(request, 'webkiosk/user_products.html', context)

def productdetail(request, pk):
    product = Food.objects.get(id=pk)
    context = {'product':product}
    return render(request, 'webkiosk/product_details.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorders(request):
    orders = request.user.customer.order_set.all()
    
    total_orders = orders.count()
    
    context={'orders':orders, 'total_orders':total_orders}
    return render(request, 'webkiosk/user_orders.html', context)
    
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorderdetails(request, pk):
    orderinfo = Order.objects.get(id=pk)
    # order = OrderItem.objects.filter(id=pk)
    order = OrderItem.objects.filter(order=pk)
    totalprice = 0
    for orderitem in order:
        totalprice += orderitem.food.price * orderitem.quantity
    context = {'order': order, 'orderinfo': orderinfo, 'totalprice': totalprice}
    return render(request, 'webkiosk/user_order_details.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userneworder(request):
    if request.method == 'GET':
        form = OrderForm()
    elif request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:userorders')
    context = {'form':form}
    return render(request, 'webkiosk/user_new_order.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorderupdate(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'GET':
        form = OrderForm(instance=order)
    elif request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            messages.success(request, 'Order successfully updated')
            return redirect('webkiosk:userorders')
    context = {'form':form}
    return render(request, 'webkiosk/user_new_order.html', context)


@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorderdelete(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'GET':
        context = {'order':order}
        return render(request, 'webkiosk/user_delete_order.html', context)
    elif request.method == 'POST':
        order.delete()
        return redirect('webkiosk:products')
    
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def usernewitem(request, pk):
    if request.method == 'GET':
        form = OrderItemForm(initial={'order': pk})
        context = {'form':form}
        return render(request, 'webkiosk/user_item_new.html', context)
    
    elif request.method == 'POST':
        form = OrderItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:userorderdetails')
        
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userupdateitem(request, pk):
    # orderitem = OrderItem.objects.get(id=pk)
    # form = OrderItemForm(instance=orderitem)
    
    # if request.method == 'POST':
    #     form = OrderItemForm(request.POST, request.FILES, instance=orderitem)
    #     if form.is_valid:
    #         form.save()
    #         messages.success(request, 'Update Sucessful!')
            
    # context = {'form': form, 'orderitem': orderitem}
    # return render(request, 'webkiosk/user_item_new.html', context)
    
    orderitem = OrderItem.objects.get(id=pk)
    if request.method == 'GET':
        form = OrderItemForm(instance=orderitem)
    elif request.method == 'POST':
        form = OrderItemForm(request.POST, instance=orderitem)
        if form.is_valid:
            form.save()
            messages.success(request, 'Update Sucessful!')
    context = {'form': form, 'orderitem': orderitem}
    return render(request, 'webkiosk/user_item_new.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userdeleteitem(request, pk):
    orderitem = OrderItem.objects.get(id=pk)
    if request.method == 'GET':
        context = {'orderitem': orderitem}
        return render(request, 'webkiosk/user_item_delete.html', context)
    elif request.method == 'POST':
        orderitem.delete()
        return redirect('webkiosk:userorders')


#############
# admin views
@admin_only
@login_required(login_url='webkiosk:login')
def dashboard(request):
    orders = Order.objects.all()
    customers = Customer.objects.all()
    foods = Food.objects.all()
    
    total_orders = orders.count()
    total_customers = customers.count()
    total_foods = foods.count()
    
    context={'orders':orders, 'customers':customers, 'total_orders':total_orders, 'total_customers':total_customers, 'total_foods':total_foods}
    
    return render(request, 'webkiosk/dashboard.html', context)

# food views
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def listfood(request):
    context = {
        'foodlist': Food.objects.all(),
    }
    return render(request, 'webkiosk/food.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def createfood(request):
    if request.method == 'GET':
        form = FoodForm()
    elif request.method == 'POST':
        #insert new form record
        form = FoodForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:food-list')
        
    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def detailfood(request, pk):
    food = Food.objects.get(id=pk)
    # orderinfo = Order.objects.get(id=pk)
    # orders = OrderItem.objects.filter(food=pk)
    # for orderitem in order:
    #     totalprice += orderitem.food.price * orderitem.quantity
        
    context = {'food':food}
    return render(request, 'webkiosk/food_detail.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def updatefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        form = FoodForm(instance=food)
    elif request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            messages.success(request, 'Food record successfully updated')
    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def deletefood(request,pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        context = {'food':food}
        return render(request, 'webkiosk/food_delete.html', context)
    elif request.method == 'POST':
        food.delete()
        return redirect('webkiosk:food-list')
    
    
# customer views
@login_required(login_url='webkiosk:login')

webkiosk/templates/webkiosk/includes/footer.html
{% load static %}

{% block css_files %} 
<link rel="stylesheet" href="{% static "webkiosk/footer.css" %}" /> 
{% endblock %} 

{% block footer %}
    <footer>
        <div class="row-1">
            <h3>Food Manager</h3>
            <p class="item"> Food Manager is a web app that helps food companies manage customers and their food orders
                for the delivery service. It also helps the company to keep track of customers and the different food
                items that they can order from the website. </p>
            <div class="footer-nav">
                <p class="download">Download Now</p>
                <p class="download">License</p>
            </div>

            <p class='item'>&copy; 2021 Nirel Ibarra and Michelle Co. All rights reserved.</p>
        </div>

        <div class="row-2">
            <h3>Site Navigation</h3>
            <a href="{% url 'webkiosk:index' %}" class='footer-links'>
                <p class='item'>Home</p>
            </a>
            <a href="{% url 'webkiosk:about' %}" class='footer-links'>
                <p class='item'>About</p>
            </a>
            <a href="" class='footer-links'>
                <p class='item'>Contact</p>
            </a>
            <a href="{% url 'webkiosk:login' %}" class='footer-links'>
                <p class='item'>Sign-In</p>
            </a>
        </div>

        <div class="row-3">
            <h3>Contact Us</h3>
            <p class="item">(+234) 137632128
                food-manager@gmail.com
                Address goes here</p>
        </div>
    </footer>
{% endblock  %}

webkiosk/templates/webkiosk/includes/navbar.html
{% load static %}

{% block css_files %} 
<link rel="stylesheet" href="{% static "webkiosk/navbar.css" %}" /> 
{% endblock %} 

{% block mainnav %}
<!-- header starts here -->
<nav class="navbar">
  <div class="navbar-container">
    <!-- insert logo here  -->
    <a href="" id="navbar-logo">
      <img src="{% static 'webkiosk/images/logo.png' %}" />
    </a>

    <div class="navbar-toggle" id="mobile-menu">
      <span class="bar"></span>
      <span class="bar"></span>
      <span class="bar"></span>
    </div>
    <ul class="navbar-menu">
      <li class="navbar-item">
        <a href="{% url 'webkiosk:index' %}" class="navbar-links">Home</a>
      </li>
      <li class="navbar-item">
        <a href="{% url 'webkiosk:about' %}" class="navbar-links">About</a>
      </li>
      <li class="navbar-item">
        <a href="#" class="navbar-links">Contact</a>
      </li>
      <li class="navbar-btn">
        <a href="{% url 'webkiosk:login' %}" class="button">Sign-In</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock  %}

<script src="{% static 'webkiosk/scripts/main.js' %}"></script>

webkiosk/templates/webkiosk/includes/user_navbar.html
{% load static %}

{% block css_files %} 
<link rel="stylesheet" href="{% static "webkiosk/navbar.css" %}" /> 
{% endblock %} 

{% block mainnav %}
<!-- header starts here -->
<nav class="navbar">
  <div class="navbar-container">
    <!-- insert logo here  -->
    <a href="" id="navbar-logo">
      <img src="{% static 'webkiosk/images/logo.png' %}" />
    </a>

    <div class="navbar-toggle" id="mobile-menu">
      <span class="bar"></span>
      <span class="bar"></span>
      <span class="bar"></span>
    </div>
    <ul class="navbar-menu">
      <li class="navbar-item">
        <a href="{% url 'webkiosk:products' %}" class="navbar-links">Products</a>
      </li>
      {% comment %} <li class="navbar-item">
        <a href="{% url 'webkiosk:cart' %}" class="navbar-links">Cart</a>
      </li> {% endcomment %}
      <li class="navbar-item">
        <a href="{% url 'webkiosk:userorders' %}" class="navbar-links">My Orders</a>
      </li>
      <li class="navbar-item">
        <a href="{% url 'webkiosk:userprofile' %}" class="navbar-links">My Profile</a>
      </li>
      <li class="navbar-btn">
        <a href="{% url 'webkiosk:logout' %}" class="button">Logout</a>
      </li>
    </ul>
  </div>
</nav>
{% endblock  %}

<script src="{% static 'webkiosk/scripts/main.js' %}"></script>