grubfood_2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('webkiosk/', include('webkiosk.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webkiosk/urls.py
from django.urls import path
from . import views

app_name='webkiosk'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('register/', views.registerpage, name='register'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    
    #For regular non-admin users
    path('userprofile/', views.userprofile, name='userprofile'),
    
    path('userorders/', views.userorders, name='userorders'),
    path('userorders/new/', views.userneworder, name='userneworder'),
    path('userorders/<int:pk>/', views.userorderdetails, name='userorderdetails'),
    path('userorders/<int:pk>/edit/', views.userorderupdate, name='userorderupdate'),
    path('userorders/<int:pk>/delete/', views.userorderdelete, name='userorderdelete'),
    
    path('usernewitem/<int:pk>/new/', views.usernewitem, name='usernewitem'),
    path('usernewitem/<int:pk>/edit/', views.userupdateitem, name='useritemupdate'),
    path('usernewitem/<int:pk>/delete/', views.userdeleteitem, name='useritemdelete'),
    
    path('products/', views.products, name='products'),
    path('products/<int:pk>/', views.productdetail, name='productdetail'),
    
    # For admin users
    path('dashboard/', views.dashboard, name='dashboard'),
    
    # Food
    path('food/', views.listfood, name='food-list'),
    path('food/new/', views.createfood, name='food-create'),
    path('food/<int:pk>/', views.detailfood, name='food-detail'),
    path('food/<int:pk>/edit/', views.updatefood, name='food-edit'),
    path('food/<int:pk>/delete/', views.deletefood, name='food-delete'),
    
    # Customer
    path('customer/', views.listcustomer, name='customer-list'),
    path('customer/new/', views.createcustomer, name='customer-create'),
    path('customer/<int:pk>/', views.detailcustomer, name='customer-detail'),
    path('customer/<int:pk>/edit/', views.updatecustomer, name='customer-edit'),
    path('customer/<int:pk>/delete/', views.deletecustomer, name='customer-delete'),
    
    #Order
    path('order/', views.listorder, name='order-list'),
    path('order/new/', views.createorder, name='order-create'),
    path('order/<int:pk>/', views.detailorder, name='order-detail'),
    path('order/<int:pk>/edit/', views.updateorder, name='order-edit'),
    path('order/<int:pk>/delete/', views.deleteorder, name='order-delete'),
    
    #Order Items
    path('orderitem/<int:pk>/new/', views.addorderitem, name='orderitem-create'),
    path('orderitem/<int:pk>/edit/', views.updateorderitem, name='orderitem-update'),
    path('orderitem/<int:pk>/delete/', views.deleteorderitem, name='orderitem-delete'),
]

webkiosk/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.id}: {self.firstname}, {self.lastname}, {self.address}, {self.city}'
    
class Food(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return f'{self.id}: {self.name}, {self.description}, {self.price}'
    
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
class Order(models.Model):
    PAYMENT_MODE_CHOICES = [
        #tuples
        ('CH', 'Cash'),
        ('CD', 'Card'),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE) 
    orderdatetime = models.DateTimeField(auto_now_add=True) 
    paymentmode = models.CharField(max_length=2, choices=PAYMENT_MODE_CHOICES) 

    # def __str__(self):
    #     return f'{self.id}: {self.customer.firstname} {self.customer.lastname}, {self.food.name}, {self.quantity}, {self.paymentmode}, {self.orderdatetime}'
    
    def __str__(self):
        return f'{self.id}: {self.customer.firstname} {self.customer.lastname}, {self.paymentmode}, {self.orderdatetime}'


class OrderItem(models.Model):

    quantity = models.IntegerField(default=1)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}: {self.order.customer.firstname} {self.order.customer.lastname}, {self.food.name}, {self.quantity}'

    def total_price(self):
        return self.food.price * self.quantity

webkiosk/forms.py
from django.forms import ModelForm, HiddenInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Customer, Food, Order, OrderItem

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['name', 'description', 'price']
        placeholders = {
            "name": "Name",
            "description": "Description",
            "price": "Price"
        }
        
class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['firstname', 'lastname', 'address', 'city']
        
class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'paymentmode']

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['order', 'food', 'quantity']
        widgets = {
            'order': HiddenInput(),
        }

class CustomerOrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'paymentmode']
        widgets = {
            'customer': HiddenInput(),
        }

# FOR THE LOGIN FORM
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

webkiosk/views.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import inlineformset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from .models import Customer, Food, Order, OrderItem
from .forms import FoodForm, CustomerForm, OrderForm, OrderItemForm, CreateUserForm
from .decorators import unauthenticated_user, allowed_users, admin_only

# Create your views here.
# main views
def index(request):
    return render(request, 'webkiosk/welcome.html')

def about(request):
    return render(request, 'webkiosk/about.html')

@unauthenticated_user
def registerpage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            Customer.objects.create(
                user=user,
            )
            
            messages.success(request, 'Account was created for ' + username)
            
            return redirect('webkiosk:login')
        
    context = {'form':form}
    return render(request, 'webkiosk/register.html', context)

@unauthenticated_user
def loginpage(request): 
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('webkiosk:dashboard')
        else:
            messages.info(request, 'Username or password is incorrect')
    context = {}
    return render(request, 'webkiosk/signin.html', context)
    
def logoutuser(request):
    logout(request)
    return redirect('webkiosk:login')

#################
# customer views
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userprofile(request):
    customer = request.user.customer
    form = CustomerForm(instance=customer)
    
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
            
    context={'form':form}
    return render(request, 'webkiosk/user_profile.html', context)

def products(request):
    context = {
        'products': Food.objects.all()
    }
    return render(request, 'webkiosk/user_products.html', context)

def productdetail(request, pk):
    product = Food.objects.get(id=pk)
    context = {'product':product}
    return render(request, 'webkiosk/product_details.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorders(request):
    orders = request.user.customer.order_set.all()
    
    total_orders = orders.count()
    
    context={'orders':orders, 'total_orders':total_orders}
    return render(request, 'webkiosk/user_orders.html', context)
    
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorderdetails(request, pk):
    orderinfo = Order.objects.get(id=pk)
    # order = OrderItem.objects.filter(id=pk)
    order = OrderItem.objects.filter(order=pk)
    totalprice = 0
    for orderitem in order:
        totalprice += orderitem.food.price * orderitem.quantity
    context = {'order': order, 'orderinfo': orderinfo, 'totalprice': totalprice}
    return render(request, 'webkiosk/user_order_details.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userneworder(request):
    if request.method == 'GET':
        form = OrderForm()
    elif request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:userorders')
    context = {'form':form}
    return render(request, 'webkiosk/user_new_order.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorderupdate(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'GET':
        form = OrderForm(instance=order)
    elif request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            messages.success(request, 'Order successfully updated')
            return redirect('webkiosk:userorders')
    context = {'form':form}
    return render(request, 'webkiosk/user_new_order.html', context)


@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userorderdelete(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'GET':
        context = {'order':order}
        return render(request, 'webkiosk/user_delete_order.html', context)
    elif request.method == 'POST':
        order.delete()
        return redirect('webkiosk:products')
    
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def usernewitem(request, pk):
    if request.method == 'GET':
        form = OrderItemForm(initial={'order': pk})
        context = {'form':form}
        return render(request, 'webkiosk/user_item_new.html', context)
    
    elif request.method == 'POST':
        form = OrderItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:userorderdetails')
        
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userupdateitem(request, pk):
    # orderitem = OrderItem.objects.get(id=pk)
    # form = OrderItemForm(instance=orderitem)
    
    # if request.method == 'POST':
    #     form = OrderItemForm(request.POST, request.FILES, instance=orderitem)
    #     if form.is_valid:
    #         form.save()
    #         messages.success(request, 'Update Sucessful!')
            
    # context = {'form': form, 'orderitem': orderitem}
    # return render(request, 'webkiosk/user_item_new.html', context)
    
    orderitem = OrderItem.objects.get(id=pk)
    if request.method == 'GET':
        form = OrderItemForm(instance=orderitem)
    elif request.method == 'POST':
        form = OrderItemForm(request.POST, instance=orderitem)
        if form.is_valid:
            form.save()
            messages.success(request, 'Update Sucessful!')
    context = {'form': form, 'orderitem': orderitem}
    return render(request, 'webkiosk/user_item_new.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['customer'])
def userdeleteitem(request, pk):
    orderitem = OrderItem.objects.get(id=pk)
    if request.method == 'GET':
        context = {'orderitem': orderitem}
        return render(request, 'webkiosk/user_item_delete.html', context)
    elif request.method == 'POST':
        orderitem.delete()
        return redirect('webkiosk:userorders')


#############
# admin views
@admin_only
@login_required(login_url='webkiosk:login')
def dashboard(request):
    orders = Order.objects.all()
    customers = Customer.objects.all()
    foods = Food.objects.all()
    
    total_orders = orders.count()
    total_customers = customers.count()
    total_foods = foods.count()
    
    context={'orders':orders, 'customers':customers, 'total_orders':total_orders, 'total_customers':total_customers, 'total_foods':total_foods}
    
    return render(request, 'webkiosk/dashboard.html', context)

# food views
@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def listfood(request):
    context = {
        'foodlist': Food.objects.all(),
    }
    return render(request, 'webkiosk/food.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def createfood(request):
    if request.method == 'GET':
        form = FoodForm()
    elif request.method == 'POST':
        #insert new form record
        form = FoodForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:food-list')
        
    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def detailfood(request, pk):
    food = Food.objects.get(id=pk)
    # orderinfo = Order.objects.get(id=pk)
    # orders = OrderItem.objects.filter(food=pk)
    # for orderitem in order:
    #     totalprice += orderitem.food.price * orderitem.quantity
        
    context = {'food':food}
    return render(request, 'webkiosk/food_detail.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def updatefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        form = FoodForm(instance=food)
    elif request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            messages.success(request, 'Food record successfully updated')
    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

@login_required(login_url='webkiosk:login')
@allowed_users(allowed_roles=['admin'])
def deletefood(request,pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        context = {'food':food}
        return render(request, 'webkiosk/food_delete.html', context)
    elif request.method == 'POST':
        food.delete()
        return redirect('webkiosk:food-list')
    
    
# customer views
@login_required(login_url='webkiosk:login')

webkiosk/templates/webkiosk/about.html
{% extends 'base.html' %}

{% load static %}

{% block pagetitle %}Grubfood WebKiosk ;){% endblock %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/main.css" %}" /> 
    <link rel="stylesheet" href="{% static "webkiosk/about.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <main>
        <div class="gradient">
            <h1 class='aboutus'>About Us</h1>
            <div class="box">
                <p><b>Food Manager</b> is a web app that helps food companies manage customers and their food orders
                    for the delivery service. It also helps the company to keep track of customers and the different
                    food items that they can order from the website.</p>
                <br>
                <p><b>Food Manager has three major functions:</b></p>
                <p>Managing Customer Data: The web app will allow users to add, view, edit, and delete customer
                    data.</p>
                <p>Managing Food Data: The web app will allow users to add, view, edit, and delete food data.</p>
                <p>Managing Order Data: The web app will allow users to add, view, edit, and delete order data.</p>
            </div>
        </div>
    </main>
{% endblock %}

webkiosk/templates/webkiosk/cart.html
{% extends 'user_base.html' %}

{% load static %}

{% block pagetitle %}Grubfood WebKiosk ;){% endblock %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/main.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <a href="{% url 'webkiosk:products' %}" class="back-btn">Back</a>
    <main>
       <h1>Cart!</h1>
    </main>
{% endblock %}

webkiosk/templates/webkiosk/customer.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block pagetitle %}Grubfood WebKiosk ;){% endblock %}

{% block css_files %} 
    {% comment %} <link rel="stylesheet" href="{% static "webkiosk/main.css" %}" />  {% endcomment %}
    <link rel="stylesheet" href="{% static "webkiosk/dashboard.css" %}" />
    <link rel="stylesheet" href="{% static "webkiosk/view_food.css" %}"> 
{% endblock %} 

{% block maincontent %}
    <main>
            <div class="top-container">
                <div class="change-view-container">
                    <a href="customers.html" class='nav-links'>
                        <svg class='list-svg' viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7 5.25H18.375" />
                            <path d="M7 10.5H18.375" />
                            <path d="M7 15.75H18.375" />
                            <path d="M2.625 5.25H2.63375" />
                            <path d="M2.625 10.5H2.63375" />
                            <path d="M2.625 15.75H2.63375" />
                        </svg>
                        List View</a>
                    <a href="customers-gallery.html" class='nav-links'>
                        <svg class='list-svg' viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7.5 2.25H2.25V7.5H7.5V2.25Z" />
                            <path d="M15.75 2.25H10.5V7.5H15.75V2.25Z" />
                            <path d="M15.75 10.5H10.5V15.75H15.75V10.5Z" />
                            <path d="M7.5 10.5H2.25V15.75H7.5V10.5Z" />
                        </svg>
                        Gallery View</a>
                </div>
                <div class="text">
                    <h1 class='caption'>Customers</h1>
                    <a href="{% url 'webkiosk:customer-create' %}" class='add-customer'>+ Add Customer</a>
                </div>

                <div class="cards-grid">
                    {% for customer in customerlist  %}
                    <a href="{% url 'webkiosk:customer-detail' customer.id %}" class='linking-card'>
                        <div class="user-card">
                            <div class="card-img">
                                <img src="../assets/personimg-1.png" alt="" class='graphic'>
                            </div>
                            <div class="card-text">
                                <h3 class='customer-name'>{{ customer.firstname }} {{ customer.lastname }}</h3>
                                <p class='status'>City: <span>{{ customer.city }}</span></p>
                                <p class="remarks">Top Buyer</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </main>
{% endblock %}

webkiosk/templates/webkiosk/customer_delete.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block pagetitle %}Grubfood - Delete {{ food.name }}{% endblock %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/delete.css" %}" />
{% endblock %} 

{% block maincontent %}
    <main>
        <img src="{% static 'webkiosk/images/delete-item.png' %}"  class='delete-btn'/>
        <h1>Delete Customer</h1>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete <b>{{ customer.firstname }} {{ customer.lastname}}</b></p>
            <a href="{% url 'webkiosk:customer-detail' customer.id %}" class="cancel">Cancel</a>
            <input type="submit" value="Yes" class="confirm">
        </form>
    </main>
{% endblock %}

webkiosk/templates/webkiosk/food.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block pagetitle %}GrubFood - Food List{% endblock  %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/view_food.css" %}" /> 
    <link rel="stylesheet" href="{% static "webkiosk/dashboard.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <main>
            <div class="top-container">
                <div class="change-view-container">
                    <a href="foods.html" class='nav-links'>
                        <svg class='list-svg' viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7 5.25H18.375" />
                            <path d="M7 10.5H18.375" />
                            <path d="M7 15.75H18.375" />
                            <path d="M2.625 5.25H2.63375" />
                            <path d="M2.625 10.5H2.63375" />
                            <path d="M2.625 15.75H2.63375" />
                        </svg>
                        List View</a>
                    <a href="foods-gallery.html" class='nav-links'>
                        <svg class='list-svg' viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7.5 2.25H2.25V7.5H7.5V2.25Z" />
                            <path d="M15.75 2.25H10.5V7.5H15.75V2.25Z" />
                            <path d="M15.75 10.5H10.5V15.75H15.75V10.5Z" />
                            <path d="M7.5 10.5H2.25V15.75H7.5V10.5Z" />
                        </svg>
                        Gallery View</a>
                </div>
                <div class="text">
                    <h1 class='caption'>Foods</h1>
                    <a href="{% url 'webkiosk:food-create' %}" class='add-customer'>+ Add Foods</a>
                </div>

                <div class="cards-grid">
                    {% for food in foodlist  %}
                    <a href="{% url 'webkiosk:food-detail' food.id %}" class='linking-card'>
                        <div class="user-card">
                            <div class="card-img">
                                {% comment %} <img src="../assets/foodimg-1.png" alt="" class='graphic'> {% endcomment %}
                            </div>
                            <div class="card-text">
                                <h3 class='customer-name'>{{ food.name }}</h3>
                                <p class='status'>P <span>{{ food.price }}</span></p>
                                <p class="remarks">Bestseller</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </main>
{% endblock %}

webkiosk/templates/webkiosk/order_form.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block pagetitle %}GrubFood - Add food{% endblock  %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/add_form.css" %}" /> 
    <link rel="stylesheet" href="{% static "webkiosk/dashboard.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <h2>Add Order</h2>
    <form method='post'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='submit'>
    </form>

    <ul>
        {% for message in messages  %}
            <li>{{ message }} </li>
        {% endfor %}
    </ul> 
{% endblock %}

webkiosk/templates/webkiosk/orderitem_form.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block pagetitle %}GrubFood - Add food{% endblock  %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/add_form.css" %}" /> 
    <link rel="stylesheet" href="{% static "webkiosk/dashboard.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <h2>Add Order Item</h2>
    <form method='post'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='submit'>
    </form>

    <ul>
        {% for message in messages  %}
            <li>{{ message }} </li>
        {% endfor %}
    </ul> 
{% endblock %}

webkiosk/templates/webkiosk/product_details.html
{% extends 'user_base.html' %}

{% load static %}

{% block pagetitle %}Grubfood WebKiosk ;){% endblock %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/main.css" %}" /> 
    <link rel="stylesheet" href="{% static "webkiosk/product_details.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <a href="{% url 'webkiosk:products' %}" class="back-btn">Back</a>
    <main>
        <div class="product-grid">
            <div class="display-img">
                <img src="{{ product.imageURL }}">
            </div>
            <div class="caption">
                <h1>{{ product.name }}</h1>
                <p>{{ product.description }}</p>
                <p>P{{ product.price}}</p>
                <div class="card-buttons">
                    <a href="{% url 'webkiosk:userneworder' %}" class="add-cart">Order Now</a>
                <div>
                <div class="more-details">
                   <p>Shipping Policy</p>
                   <p>Returns and Refunds</p>
                <div>
            </div>
        </div>
    </main>
{% endblock %}

webkiosk/templates/webkiosk/signin.html
{% extends 'base.html' %}

{% load static %}

{% block pagetitle %}Sign-in Page{% endblock %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/signin.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <main>
        <div class="graphics-container">
            <img src="{% static 'webkiosk/images/logingraphic.png' %}" alt="Login" class='login-image'>
        </div>
        <div class="login-container">
            <div class="text">
                <h1>Welcome!</h1>
                <p className="desc">kindly fill in your login details to proceed</p>
            </div>
            <form method='POST' id='form'>
                {% csrf_token %}
                <input type="text" name="username" value="Username">
                <input type="password" name="password">
                <p>Don't have an account? <a href="{% url 'webkiosk:register' %}" class='forgot-pass'>Register</a></p>
                <input type="submit" value='Sign-In' class="btn-signin">
                <!-- <button class='signin'>Sign-In</button> -->
            </form>
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    </main>
{% endblock %}

webkiosk/templates/webkiosk/user_products.html
{% extends 'user_base.html' %}

{% load static %}

{% block pagetitle %}Grubfood WebKiosk ;){% endblock %}

{% block css_files %} 
    <link rel="stylesheet" href="{% static "webkiosk/view_food.css" %}" /> 
{% endblock %} 

{% block maincontent %}
    <main>
        <h1>Food Menu</h1>
        <div class="cards-grid">
            {% for product in products  %}
                <a href="{% url 'webkiosk:productdetail' product.id %}" class='linking-card'>
                    <div class="user-card">
                        <div class="card-img">
                        {% comment %} supposed to be product.image.url {% endcomment %}
                            <img src="{{ product.imageUrl }}" alt="{{ product.name }}" class='graphic' />
                        </div>
                        <div class="card-text">
                            <h3 class='customer-name'>{{ product.name }}</h3>
                            <p class='status'>P <span>{{ product.price }}</span></p>
                            <p class="remarks">Bestseller</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
            </div>
    </main>
{% endblock %}